In [1]:
import numpy as np

In [2]:
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0, 10, 2)
print(a2)

[0 2 4 6 8]


In [4]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [5]:
a4 = np.zeros((2,3))
print(a4.shape)

(2, 3)


In [6]:
print(a4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#a4 is the creating of a two dimensional array.  If we want to create an array filled with a specific number instead of 0, use the full() function as shown below:

In [8]:
a5 = np.full((2,3), 8)
print(a5)

[[8 8 8]
 [8 8 8]]


In [9]:
#Sometimes, you need to create an array that mirrors an identity matrix.  We can do this using an eye() function, as shown below:

In [10]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#The eye() function returns a 2-D array with ones on the diagonal an zeros elsewhere.  To put random numbers anywhere, we can use the random() function, as shown below:

In [12]:
a7 = np.random.random((2,4))
print(a7)

[[0.85993969 0.1963764  0.97432995 0.84477275]
 [0.30616627 0.7254448  0.1011863  0.70558365]]


In [13]:
#Another way to create Numpy arrays is to create it from a python list as follows:

In [14]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1)

#This is an example of a rank 1 array.

[1 2 3 4 5]


In [15]:
#Now we're going to get into array indexing.

In [16]:
#The following code snippet creates another array named r2, which is two dimensional:

In [17]:
list2 = [6, 7, 8, 9, 0]
r2 = np.array([list1, list2])
print(r2)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [18]:
#Now we can use indexing to locate values:

In [19]:
print(r2.shape)

(2, 5)


In [20]:
print(r2[0, 0])

1


In [21]:
print(r2[0, 1])

2


In [22]:
print(r2[1, 0])

6


In [23]:
#Besides using an index to access elements in an array, you can also use a list as the index as follows:

In [24]:
list1 = [1, 2, 3, 4, 5]
r1 = np.array(list1)
print(r1[[2,4]])

[3 5]


In [25]:
#Boolean Indexing

In [26]:
#Say for example that you want to retrieve all the odd numbers in the array, you could simply use Boolean indexing as follows:

In [27]:
nums = np.arange(20)
odd_num = nums[nums % 2==1]
print(odd_num)

[ 1  3  5  7  9 11 13 15 17 19]


In [28]:
#Slicing Arrays

In [29]:
#Slicing in NumPy arrays is similar to how it works with a Python List.  Consider the following:

In [30]:
a = np.array ([[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [9, 8, 7, 6, 5]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [31]:
#To extract the last two rows and first two columns, you can use slicing, as follows:

In [32]:
b1 = a[1:3, :3]
print(b1)

[[4 5 6]
 [9 8 7]]


In [33]:
#What about negative indices?  Consider the following:

In [34]:
b2 = a[-2:, -2:]
print(b2)

[[7 8]
 [6 5]]


In [35]:
#It is Noteworthy that the result of a NumPy slice is a reference and not a copy of the original array.  Consider the following:

In [36]:
b3 = a[1:, 2:]
print(b3)

[[6 7 8]
 [7 6 5]]


In [37]:
#If you were to change one of the elements in b3 as follows:

In [38]:
b3[0, 2] = 88
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7 88]
 [ 9  8  7  6  5]]


#The result will affect the original array.

In [39]:
#another salient point to note is that the result of the slicing is dependent on how you slice it.  Here's an example:

In [40]:
b4 = a[2:, :]
print(b4)
print(b4.shape)

[[9 8 7 6 5]]
(1, 5)


In [42]:
#The result above is a rank 2 array#

In [ ]:
#you can reshape an array to another dimension using the reshape() function.  Using the b5, you can reshape to a rank 2 array as follows:

In [43]:
b5 = a[2, :]
b5 = b5.reshape(1, -1)
print(b5)

#In this example, you call the reshape() function with wto arguments.  The first 1 indicates that you want to convert it into rank 2 array with 1 row, and the -1 indicates that you will leave it to the reshape() function to create the correct number of collumns.

[[9 8 7 6 5]]


In [ ]:
#If you want to convert a rank 2 to a rank 1, use the flatten() or ravel() functions.

In [ ]:
#Array Math!  You can perform array math very easily with NumPy arrays.

In [ ]:
#you can add two arrays together as follows with the + operator:

In [45]:
x1 = np.array([[1, 2, 3] , [4, 5, 6]])
y1 = np.array([[7, 8, 9] , [2, 3, 4]])
print(x1 + y1)

[[ 8 10 12]
 [ 6  8 10]]


In [ ]:
#array math can be used to perform vector calculations, as follows:

In [46]:
x = np.array([2,3])
y = np.array([4,2])
z = x + y


In [ ]:
#the same can be done for subtraction, multiplication and division.

In [ ]:
#Dot product.  Note that when you're multiplying two arrays, you are actually multiplying each of the corresponding elements in the two arrays.  Very often, you want to perform a scalar product.  It takes two coordinate vectors of equal size and returns a single number.  Example is as follows:

In [47]:
x = np.array([2, 3])
y = np.array([4,2])
np.dot(x, y)

14

In [ ]:
#You can also use a matrix.  The matrix class is a subclass of the ndarray, and it is basically identical to the ndarray with one notable exception, a matrix is strictly two dimentional, where as an ndarray is multidimensional.  

# An example as follows:

In [48]:
x1 = np.array([[1, 2] , [4, 5]])
y1 = np.array([[7, 8] , [2, 3]])
x1 = np.asmatrix(x1)
y1 = np.asmatrix(y1)